# Generated by Django 5.0.6 on 2024-07-07 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_video_quality_video_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
