# Generated by Django 5.0.6 on 2024-07-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_video_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="play",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="video",
            name="q360",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="video",
            name="q720",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
